name: React app deployement

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy React code to GitHub Pages
    uses: amitsingh-007/deploy-to-github-pages@v1.2
